name: Build C25 Docker Image
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t constellation-25 .
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push to DockerHub
        run: |
          docker tag constellation-25 faceprintpay/constellation-25:latest
          docker push faceprintpay/constellation-25:latest
